[[pugixml]]
arch = "aarch64"
git-tree-sha1 = "e7fd02631aabec3626b06de0aed4038194e80f58"
os = "macos"

    [[pugixml.download]]
    sha256 = "6a52820b8cdc37452bbf38396a9a2d4dd3d5569af47613c7cbb38fef281e2c21"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.aarch64-apple-darwin.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7db3f06e67120bd4b893264291d660e71c6e33e7"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "7278e17ede37ab059b51c673a8dcb9d470e821c128cf110c18a703638e5867f3"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.aarch64-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7376947756b8ccdf69815c79e12a2c9bdceb81cf"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "8cb7518fca195a92fc17ea1957652f65071fc6ccd319e7088fbb0245e09bf9c1"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.aarch64-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5e2677a5f5b816577b8dff378475426bcca67f5"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "f5b9cbcaab0b44297962047031feefe9b0bf98ad51ab327d7d8b4939c26a83f6"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.aarch64-linux-musl-cxx03.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c9cd6e716469d6fa1b7528125a83f2f3d3cedaa"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "d123223ab84c0f143e4813bdc010488d0e7fb5356f3863a361380d111801130c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.aarch64-linux-musl-cxx11.tar.gz"
[[pugixml]]
arch = "aarch64"
git-tree-sha1 = "9f81908a69200cfde877c9efe35608154828c523"
os = "freebsd"

    [[pugixml.download]]
    sha256 = "5257362c0e6b0e452841020d8489a64d8ebc238badad0bba9ae22d3464c2a1e7"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.aarch64-unknown-freebsd.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64d871c335dc85153570ba6efabfdb3a9de4da7f"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "7373e1813810bf4903fb5b36c417ee90b71e375c12a13ab5af92963d99245ae3"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe3b1802fa99e66e028518a8147af198143312d7"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "eb44f3eb21135a9176466e7d68fdf5186daa17703f2ff155b7ee817ec5ebf6c2"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "966e8c0455476a4add5ae502a5aa4774911bf8f9"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "97fb4011aa72cb3e992aad600133f863fa28411a0d96888da15d3e964a581dd2"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b567576ff77fd95f8a43b115f26ea43157a46840"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "94b4a601e3604a77ab9e35865f312d0829ddbe8dcd0352d6e89589327aa7716c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b4e6fc642eb519287ed340f0954586812224aab"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "956f758e418ff310e7cf79955ef23d419d734ca5268d23fae6d5671d26021b0d"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dd95df4053afae546d3e83f8b4991ca17da817b"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "afdcb37b06619eb30f34f9f59c72a9ee30cdb59baedb8485e32c47ab3b302338"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9c9ffa4478b0516740131bbb181b98bba64ea4f"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "dbcda1c3b57f75961922648bbf5dd73fcf05504fef880911f6d0e0b659b41d17"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07f0309cf3d281e3241591f57ea85700ec18a9f2"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "a7c5f30f7098c03bfe8c18cd3f45cad8fdd61fdafd1ccbdcb7af31865fcd4437"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e89dde5a95ff77dbe575678242d023d95830374"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "94fa24be28da0cb5371fc9ce29699c6d5d8b13238e126dbd1b527432a593bbcc"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.i686-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7816634ff21945a97b8d37049c7c64c924008e1"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "39ac77cb6b985effb29da25c0f6e70b952cd8f2632cfb91299e7df9437c89cf4"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.i686-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f54c5ee68b7647ca98558eea7e9be4248f0f0297"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "225ea5af79773c376159430950bbf3c237b72fd3f1926b135712b6af729954c5"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.i686-linux-musl-cxx03.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f7a223a44c9214bf26f7725d3461e79cfe7650b"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "c5c2cf6bf873b790350ffb041a2d452dd12174dead560ea4b1c9b0cecf8c633d"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.i686-linux-musl-cxx11.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec929102bbdbb502837928f5124c78f5f48b98a3"
os = "windows"

    [[pugixml.download]]
    sha256 = "f4c99a3ea292c437abbf10d96cb11c62e8df7e14aec9b1bf53af50f39afc32d1"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.i686-w64-mingw32-cxx03.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92c6a31becd04703be162a6d8f1a29faf49e1641"
os = "windows"

    [[pugixml.download]]
    sha256 = "0502127f184cbc6625ad1b1c760df984b27284c234e4f29a620f944261d025d0"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.i686-w64-mingw32-cxx11.tar.gz"
[[pugixml]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70a82dc815acdd6ff1c070c79e667596320a4d18"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "aa5794a2797d4b998e8c00e534bf5ce23f62f816ed071661bd84c16b5efd9302"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f2af3925dc24d6e5b1a7cb513b0bc026bf49238"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "5c96a34aa01eb76ba6340d0037080f1f223aecb83cb2e52c74553f55da5da1b5"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "x86_64"
git-tree-sha1 = "3172fea3c3f72db845bc402e8892c07efedd7418"
os = "macos"

    [[pugixml.download]]
    sha256 = "3e5c5e30e2ae39c179609cfafccf58f81fb7371a20262ec7e1a742fa457e2f0e"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-apple-darwin.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a163e01293e6fe9f3254f5a15f811e6bd883faa"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "d305d441313ebaf3ac63dfa5e50cb7d3ed02ae530b9152c52d500fea47557fb0"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d534b4b64cd86c7e7eccb86f31917980f747e9b0"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "1e0478d2ee445f3ccc2c3265a3fd385151b567a3dc8f07ed4e3ddddd0289912f"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a51f33333f999e08a9665e1cfca702daf49a0307"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "0fea9dbfcc4f85da68c4d4cdde0f3507a0afd77b443cde1f235020df87b04a2c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-linux-musl-cxx03.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73d15224cc942bc97fcadb6803ce617e91acab30"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "d2404d9e2b0bb6994c7fac795ad8d29c5fd7ad85b0e26b494da8ab6fb7514dbe"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-linux-musl-cxx11.tar.gz"
[[pugixml]]
arch = "x86_64"
git-tree-sha1 = "b9bd29c01e16999d6089a1120b56d7775461f4e3"
os = "freebsd"

    [[pugixml.download]]
    sha256 = "37303b4cdc68f30e8b434386f7e4fe97beb74802ab2da139facdb23377e2b164"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-unknown-freebsd.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74585e66ca65fb0fa51122a439348e3ddd9bdc90"
os = "windows"

    [[pugixml.download]]
    sha256 = "2d40f72dce13532d282f8fa12f8d3a75fab30ad997c6a8e7e42d8213bcd39123"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4aaed06845bc40933ebb778215075a0e818e0836"
os = "windows"

    [[pugixml.download]]
    sha256 = "fe89cbc9c0c285a4136cc58a525a476024133ae92e0fb197cc6fba7adc715871"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.14.0+0/pugixml.v1.14.0.x86_64-w64-mingw32-cxx11.tar.gz"
