[[pugixml]]
arch = "aarch64"
git-tree-sha1 = "ded8811c113da0d6c2746b2a07f30e282cb59515"
os = "macos"

    [[pugixml.download]]
    sha256 = "113fa43924f617018bef5d23cfd6d3940900d4646df0f149df7b5a2d5959bd9c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.aarch64-apple-darwin.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9285a93d545db3786678744db3f91c68f179f36"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "f63f75bfe3531f0ad3ee3004a6070c6a330ed32d25a795c94d5b88100c710cb8"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.aarch64-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fac5a1f0dc8b0b9f3ffc32565de7ca8be329c32c"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "b267d87af7141dacd20a8bbecee737d9293d546a00f3cb70910529d27aeb650a"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.aarch64-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1aaf89ea24d4e5999b477ccd1bf06e398c03765"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "ee98332ec57d2e99e0b76d0c8f6f38bcb2672df6379a7be237f45088e8081221"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.aarch64-linux-musl-cxx03.tar.gz"
[[pugixml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd0201a1bc2d90d48b4c2a96418ac6a7f1f0ff1e"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "b78b76909ccf7d401ed36dc4f312f3274fd135a3d871a601739d3b61f0790439"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.aarch64-linux-musl-cxx11.tar.gz"
[[pugixml]]
arch = "aarch64"
git-tree-sha1 = "5a15322a7e5a01939eec1e44597cbd16905ec1c0"
os = "freebsd"

    [[pugixml.download]]
    sha256 = "6fe2230757fa1968ba18c30a539455bc1d479a851eed62bca9b5e2838e1c496c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.aarch64-unknown-freebsd.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "044f7d0d2164be5b9e339f0bb40fe035180e980d"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "877bb556cfe0ee782a289e0a70595038cfd8d7ca7a08502c0b960bda23391107"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddc2d5185a564363c4cc9e51862fe3d7bb7ba4f1"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "ac333f18ac632210ead79a9ea31327c20bd3c56047742846b5a80198c802d1f0"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72522d12939127f08df2c621cbea67da074d0315"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "acb93bda30cecfea81b6fe0730d59bf7d0d628ecba7156d17933d54804c32972"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aece3b2911ef8193999d65ce1117bf88f71ef260"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "142b6a221bbef1b5132458bf419b9d736129e3d5f361be7d566eade0ccb50810"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbf096941faaa733edebec7518fc06b4ed731588"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "5504fb782eae53c3c4c9ad4a597fbad4ec760c00bf9d9ce0f6f89e74811b3dda"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e49b6a8d6fd2d06ebe760025929258e870f70021"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "fbc9cecf9e8483feaf66a0f0cec1ee20f194b9379e965ab35c374798170e5ad6"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6a9424930ea49cadfc63818860e667d79b39547"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "1fe2b070a445514373265557351bf89eb44dfef974aa69fc1641bd3aa3268e0a"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[pugixml]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0564dad8fb59ee0df594abca0ecd69016aa4e68"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "3a4401b907c0a6d9fc125669313724627f3105487166e00d52820f80f4dceb2c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd531988ab09fd4dd8c47174a02e1bf6de5eba31"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "f8d771c6e50ad79fbb525ca52f3bc6daea0540fea2be005aa79b3f6c61cc4cca"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.i686-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "781b5b92c424edd5d58c6384ca1409ed2da1e88a"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "eabddda22574b407554c2486d8845106cd0c4fa3f9c4d7d5fcf04e55189d3e4a"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.i686-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28db228f368d62fa7dc0a300ab45ae62c99c56ba"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "d227d2b2bf0a59ff29a45411a5c375679f682ef678e49d7f800ed92b6d062312"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.i686-linux-musl-cxx03.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcf61792530d387cae740978947dcb4cc6934a4e"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "9547a7a58961cc5d9aca0730006350852b079345120fd05f310f2ca4c8453f78"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.i686-linux-musl-cxx11.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f86489cc86dbd0d0e84de390f4cf79ca449f591"
os = "windows"

    [[pugixml.download]]
    sha256 = "4833e44d70496ec748ca2608e6b78dfd18416119174b0e926a8c158225b87eb6"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.i686-w64-mingw32-cxx03.tar.gz"
[[pugixml]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b2476d95e1ca0c513d8598de3084c3214b4ee22"
os = "windows"

    [[pugixml.download]]
    sha256 = "2b780eac750a78d44121a805c170f776228b84dd2fcb30c8b93e53675fec898b"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.i686-w64-mingw32-cxx11.tar.gz"
[[pugixml]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09b4d771bd4c8b9d5e3a5fcd28de12f37d880ee9"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "6bd0036a5815c1d49c396039c570c60e266ed49495bc8360fdadc9543b07700c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f98b43df457c74997a0144fd1b359c8f8e5da371"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "1909f4ca3a91448512df6150ff6901a6b1baa6591d977ab217b57b2abb6a534e"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e24561139ad32cd9923fc2665637da43245e313"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "30b375bdf6957dd903ded69ca8f06743549fcb05d3bdc9ae73f54e4a51ba97ea"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.riscv64-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ecaab71dfafab98837baa068f3ee1b1d492b1b8"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "353e9834879b8f37998ff37debfdce608922983781a395c42bdafb00d903de2c"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.riscv64-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "x86_64"
git-tree-sha1 = "8cf4ae89378cb4e530b315b631e62f6f73b1858c"
os = "macos"

    [[pugixml.download]]
    sha256 = "6c13d1d3efa7a106fbb918d0fd1097d66849321d85dea023bb3ba3f86eb15aca"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-apple-darwin.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f94ddbce85987718af8732fdad5104f2c4d3714b"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "55da0384067d048c38ca9882c89c0c22f3cb0ebf0184268aae586057be44586d"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-linux-gnu-cxx03.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28df058ba0d319bba434f3b93e61f8ff05e7ee38"
libc = "glibc"
os = "linux"

    [[pugixml.download]]
    sha256 = "e2d1dd176ac2c918609d6761636b997ea1b572fba597ae49e988661fa95a15e2"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-linux-gnu-cxx11.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d3295699725ec0d92afdaf021a51349bcc82aca"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "cdb0d0028fe2be7c1938df1b4381a0b239fa0165fd8152601796a89d9216ce3b"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-linux-musl-cxx03.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaff940eaf59942ed1bf9882bda90dbb5f1c47a6"
libc = "musl"
os = "linux"

    [[pugixml.download]]
    sha256 = "c64561d79aec0fc64555f4e677614141c6fda77a5dcac3ce1058906e8836d7bb"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-linux-musl-cxx11.tar.gz"
[[pugixml]]
arch = "x86_64"
git-tree-sha1 = "226f6479131ee5b8c717bcd6f4f4d850ccb7e9f0"
os = "freebsd"

    [[pugixml.download]]
    sha256 = "30641e064ca17750b5409a3e8c26ac44599a2ae8f6b6b6f5fbb037173409c052"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-unknown-freebsd.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dee71a4068922892cec6075ec67c5ad0c007b7fa"
os = "windows"

    [[pugixml.download]]
    sha256 = "d9b8d058379139da12a17b90b80f03469f3712f3880d9aad771da9f560cf1185"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[pugixml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf555d0ac46c64465433685be1dd9512b4b4a253"
os = "windows"

    [[pugixml.download]]
    sha256 = "9b7e2b8a44470ba17ba32120e0e4e2bf0dbfd9d818302304e9e9ea01eab217de"
    url = "https://github.com/JuliaBinaryWrappers/pugixml_jll.jl/releases/download/pugixml-v1.15.0+0/pugixml.v1.15.0.x86_64-w64-mingw32-cxx11.tar.gz"
